name: server1
version: 0.1.0.0
github: 'githubuser/server1'
license: BSD3
author: 'Author name here'
maintainer: 'example@example.com'
copyright: '2022 Author name here'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/server1#readme>

default-extensions:
  # - ParallelListComp
  # - TransformListComp
  # - MonadComprehensions
  - OverloadedLists
  # - PostfixOperators
  - TupleSections
  - LambdaCase
  - EmptyCase
  - MultiWayIf
  - BlockArguments
  # - EmptyDataDecls
  - TypeOperators
  # - ExplicitNamespaces
  # - LiberalTypeSynonyms
  # - ExistentialQuantification
  # - GADTSyntax
  - GADTs
  - TypeFamilies
  # - TypeFamilyDependencies
  - DataKinds
  # - TypeInType
  # - PolyKinds
  # - StandaloneKindSignatures
  # - StarIsType
  - TypeApplications
  # - RankNTypes
  # - ImpredicativeTypes
  # - RoleAnnotations
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - NamedFieldPuns
  - RecordWildCards
  # - EmptyDataDeriving
  - StandaloneDeriving
  # - DeriveFunctor
  # - DeriveFoldable
  # - DeriveTraversable
  # - DeriveDataTypeable
  # - DeriveLift
  - GeneralizedNewtypeDeriving
  - DeriveAnyClass
  # - DerivingStrategies
  - DerivingVia
  # - ViewPatterns
  # - PatternSynonyms
  - MultiParamTypeClasses
  - TypeSynonymInstances
  - FlexibleInstances
  - NumericUnderscores
  - OverloadedStrings
  - FlexibleContexts
  # - ConstraintKinds
  # - ExplicitForAll
  # - KindSignatures
  - ScopedTypeVariables
  # - BangPatterns
  - StrictData
  - Strict
  - DeriveGeneric
  - NoImplicitPrelude
  # - TemplateHaskell
  - QuasiQuotes
  # - UndecidableInstances
  # - AllowAmbiguousTypes
  # - OverlappingInstances
  # - IncoherentInstances
  # - OverloadedLabels

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - async
  - rapid
  - pretty-simple
  - chronos-bench
  - servant
  - servant-server
  - servant-errors
  - warp
  - wai-logger
  - universum
  - unliftio
  - beam-core
  - beam-postgres
  - beam-migrate
  - postgresql-simple
  - dotenv

library:
  source-dirs: src

executables:
  server1-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - server1

tests:
  server1-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - server1
